import type { Metadata } from "next";
import { Crimson_Pro, Montserrat } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components";

const crimson_init = Crimson_Pro({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-crimson'
});

const montserrat_init = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-montserrat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${crimson_init.variable} ${montserrat_init.variable}`}>
        <div className="flex">
          <nav className="z-50">
            <Sidebar />
          </nav>
          
          <main className="flex-1 bg-stonks-100 pt-[25px] md:pt-0">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
