import type { Metadata } from "next";
import { Crimson_Pro, Lexend } from "next/font/google";
import "./globals.css";
import { Sidebar } from "@/components";
import { AuthContextProvider } from "@/context/AuthContext";

// const crimson_init = Crimson_Pro({
//   subsets: ['latin'],
//   weight: ['700'],
//   variable: '--font-crimson'
// });

const lexend_init = Lexend({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-lexend',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${lexend_init.variable}`}>
        <AuthContextProvider>
        <div className="flex">
          <nav className="z-50">
            <Sidebar />
          </nav>
          
          <main className="flex-1">
            {children}
          </main>
        </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
