import type { Metadata } from "next";
import { Crimson_Pro, Montserrat } from "next/font/google";
import "./globals.css";

const crimson_init = Crimson_Pro({
  subsets: ['latin'],
  weight: ['700'],
  variable: '--font-crimson'
});

const montserrat_init = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-montserrat'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${crimson_init.variable} ${montserrat_init.variable}`}>
        {children}
      </body>
    </html>
  );
}
